::__tagarray <-  [
    "popext_mobber"
    "popext_customattr|crit when health below|0.5"
    "popext_customatr|projectile gravity|500"
    "popext_customattr|explosive bullets|147"
    "popext_customattr|add cond on hit|71|1"
    "popext_customattr|arrow ignite|1"
    "popext_customattr|mult projectile scale|1.3"
    "popext_customattr|crit when health below|0.5"
    "popext_rocketcustomtrail|spell_fireball_small_red"
    "popext_rocketcustomtrail|rocketpack_exhaust"
    "popext_rocketcustomtrail|eyeboss_projectile"
    "popext_usecustommodel|models/bots/soldier_boss/bot_soldier_boss_gibby.mdl"
    "popext_usecustommodel|models/bots/heavy_boss/bot_heavy_boss_gibby.mdl"
    "popext_usecustommodel|models/bots/soldier/goliatron2022_v3.mdl"
    "popext_spawnhere|38, 815, -400|2"
    "popext_ringoffire|20|2"
    "popext_reprogrammed"
    "popext_fireweapon|2048"
    "popext_usehumananims"
]